In [1]:

"""Test script for single agent problems.

This scripts runs the best model found by one of the executions of `singleagent.py`

Example
-------
To run the script, type in a terminal:

    $ python test_singleagent.py --exp ./results/save-<env>-<algo>-<obs>-<act>-<time_date>

"""
import os
import time
from datetime import datetime
import argparse
import re
import numpy as np
import gym
import pprint
import torch

from gym_pybullet_drones.utils.utils import sync
from gym_pybullet_drones.utils.Logger import Logger
from gym_pybullet_drones.envs.single_agent_rl import NavigateLandAviary

from gym_pybullet_drones.envs.single_agent_rl.BaseSingleAgentAviary import (
    ActionType,
    ObservationType,
)
import pybullet as p

import shared_constants

/home/mtrang/anaconda3/envs/drones/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
pybullet build time: May 20 2022 19:44:17


In [2]:

env_name = "land-aviary-v0"
OBS = (
    ObservationType["KIN"]
)
ACT = ActionType["RPM"]
landing_zone_xyz = [3.5, 3.5, 0.0625]
#### Evaluate the model ####################################
env = gym.make(
    env_name,
    aggregate_phy_steps=shared_constants.AGGR_PHY_STEPS,
    obs=OBS,
    act=ACT,
    gui=True,
    initial_xyzs = [[3.57, 3.57,0.25]],
    landing_zone_xyz =  landing_zone_xyz,
)
env.reset()

[INFO] BaseAviary.__init__() loaded parameters from the drone's .urdf:
[INFO] m 0.027000, L 0.039700,
[INFO] ixx 0.000014, iyy 0.000014, izz 0.000022,
[INFO] kf 0.000000, km 0.000000,
[INFO] t2w 2.250000, max_speed_kmh 30.000000,
[INFO] gnd_eff_coeff 11.368590, prop_radius 0.023135,
[INFO] drag_xy_coeff 0.000001, drag_z_coeff 0.000001,
[INFO] dw_coeff_1 2267.180000, dw_coeff_2 0.160000, dw_coeff_3 -0.110000
viewMatrix (-0.8660253882408142, -0.2499999701976776, 0.4330126941204071, 0.0, 0.0, 0.8660253286361694, 0.4999999701976776, 0.0, -0.4999999701976776, 0.4330126643180847, -0.75, 0.0, -0.0, 5.960464477539063e-08, -2.999999761581421, 1.0)
projectionMatrix (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0000200271606445, -1.0, 0.0, 0.0, -0.02000020071864128, 0.0)
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsy

/home/mtrang/anaconda3/envs/drones/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


array([ 0.119,  0.119,  0.025,  0.   , -0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ])

In [14]:
env.reset()

array([ 0.119,  0.119,  0.025,  0.   , -0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ])

In [ ]:

done = False
while not done:
    env.render()
    action = env.action_space.sample()
    action = -1 * np.ones_like(action)
    time.sleep(0.05)
    obs, reward, done, info = env.step(action)
    if done:
        env.reset()


In [ ]:
p.loadURDF("cube.urdf", [0, 0, 0.5], physicsClientId=env.CLIENT)

#Single Step of env and print state

In [24]:

action = env.action_space.sample()
action = -1 * np.ones_like(action)
for i in range(20):
    time.sleep(0.05)
    obs, reward, done, info = env.step(action)
    state = env.getFirstDroneState()
    print(f"action: {action}")
    print(f"obs: {obs}")
    print(f"reward: {reward}")
    print(f"done: {done}")
    print(f"state: {state}")
    env.render()


action: [-1. -1. -1. -1.]
obs: [ 1.19034353e-01  1.18963552e-01  1.38474985e-02 -2.26949245e-05
 -2.66139605e-05 -5.23243718e-01 -3.51337162e-06 -5.72373414e-06
  2.51083274e-05  7.25057919e-01 -6.88628559e-01 -9.03999017e-03]
reward: 0
done: False
state: [ 3.57103060e+00  3.56890656e+00  1.38474985e-01 -5.48907961e-05
 -2.35084060e-06 -7.32447068e-01  6.80823978e-01 -7.12982081e-05
 -8.36102227e-05 -1.64381862e+00 -1.05401148e-05 -1.71712024e-05
  7.53249822e-05  1.17253589e-03 -1.11362373e-03 -1.46191258e-05
  1.37450068e+04  1.37450068e+04  1.37450068e+04  1.37450068e+04]

[INFO] BaseAviary.render() ——— it 0305 ——— wall-clock time 3800.7s, simulation time 1.3s@240Hz (0.00x)
[INFO] BaseAviary.render() ——— drone 0 ——— x +03.57, y +03.57, z +00.14 ——— velocity -00.00, -00.00, +00.00 ——— roll -00.00, pitch -00.00, yaw -94.18 ——— angular velocity +0.0012, -0.0011, -0.0000 ——— 
action: [-1. -1. -1. -1.]
obs: [ 1.19034348e-01  1.18963543e-01  1.38476216e-02 -1.73644739e-05
 -2.01106918e-05

In [21]:
# try and flip
action = env.action_space.sample()
action = -1 * np.ones_like(action)
action[0] = 1
action[2] = 1
print(action)
for i in range(5):
    time.sleep(0.05)
    obs, reward, done, info = env.step(action)
    state = env.getFirstDroneState()
    print(f"action: {action}")
    print(f"obs: {obs}")
    print(f"reward: {reward}")
    print(f"done: {done}")
    print(f"state: {state}")
    env.render()

[ 1. -1.  1. -1.]
action: [ 1. -1.  1. -1.]
obs: [ 0.119       0.119       0.0251372   0.          0.         -0.53441897
  0.          0.          0.00270417  0.          0.         -1.        ]
reward: 0
done: False
state: [ 3.57000000e+00  3.57000000e+00  2.51372012e-01  0.00000000e+00
  0.00000000e+00 -7.44284818e-01  6.67862344e-01  0.00000000e+00
  0.00000000e+00 -1.67892670e+00  0.00000000e+00  0.00000000e+00
  8.11249557e-03  0.00000000e+00  0.00000000e+00 -9.71905653e+00
  1.51918496e+04  1.37450068e+04  1.51918496e+04  1.37450068e+04]

[INFO] BaseAviary.render() ——— it 0080 ——— wall-clock time 3778.0s, simulation time 0.3s@240Hz (0.00x)
[INFO] BaseAviary.render() ——— drone 0 ——— x +03.57, y +03.57, z +00.25 ——— velocity +00.00, +00.00, +00.01 ——— roll +00.00, pitch +00.00, yaw -96.20 ——— angular velocity +0.0000, +0.0000, -9.7191 ——— 
action: [ 1. -1.  1. -1.]
obs: [ 0.119       0.119       0.02515473  0.          0.         -0.60105466
  0.          0.          0.00287197  0

In [26]:

landing_zone_xyz = [3.5, 3.5, 0.0625]
position = state[0:3]
print(position)
target_position = landing_zone_xyz
pos_dist = np.linalg.norm(position[0:2] - target_position[0:2])
print(pos_dist)

y_dist = np.linalg.norm(position[2] - (target_position[2] - 0.1))
print(y_dist)

[3.57103166 3.56890536 0.13847858]
0.0989618379966182
0.17597858384844264


In [20]:

rpy = state[7:10]
print(rpy)

[ 0.          0.         -1.48107308]


In [ ]:
# Change initial position of the drones

In [ ]:
env.reset()
p.resetSimulation()