In [1]:

"""Test script for single agent problems.

This scripts runs the best model found by one of the executions of `singleagent.py`

Example
-------
To run the script, type in a terminal:

    $ python test_singleagent.py --exp ./results/save-<env>-<algo>-<obs>-<act>-<time_date>

"""
import os
import time
from datetime import datetime
import argparse
import re
import numpy as np
import gym
import pprint
import torch

from gym_pybullet_drones.utils.utils import sync
from gym_pybullet_drones.utils.Logger import Logger
from gym_pybullet_drones.envs.single_agent_rl import NavigateLandAviary
from gym_pybullet_drones.envs.single_agent_rl import map_name_to_env

from gym_pybullet_drones.envs.single_agent_rl.BaseSingleAgentAviary import (
    ActionType,
    ObservationType,
)
import pybullet as p
import pybullet_data

import shared_constants

pybullet build time: May 20 2022 19:44:17


In [2]:

#env_name = "land-aviary-v0"
env_name = "cross-obstacles-aviary-v0"
#env_name = "room-aviary-v0"

OBS = (
    ObservationType["KIN"]
)
ACT = ActionType["RPM"]
landing_zone_xyz = [3.5, 3.5, 0.0625]
#### Evaluate the model ####################################
env = gym.make(
    env_name,
    aggregate_phy_steps=shared_constants.AGGR_PHY_STEPS,
    obs=OBS,
    act=ACT,
    gui=True,
    initial_xyzs = [-0.5, 0, .5],
)
env.reset()

[INFO] BaseAviary.__init__() loaded parameters from the drone's .urdf:
[INFO] m 0.027000, L 0.039700,
[INFO] ixx 0.000014, iyy 0.000014, izz 0.000022,
[INFO] kf 0.000000, km 0.000000,
[INFO] t2w 2.250000, max_speed_kmh 30.000000,
[INFO] gnd_eff_coeff 11.368590, prop_radius 0.023135,
[INFO] drag_xy_coeff 0.000001, drag_z_coeff 0.000001,
[INFO] dw_coeff_1 2267.180000, dw_coeff_2 0.160000, dw_coeff_3 -0.110000
startThreads creating 1 threads.
starting thread 0
viewMatrix (-0.0, -0.6427876353263855, 0.7660444378852844, 0.0, 0.0, 0.7660444378852844, 0.6427876353263855, 0.0, -1.0, 0.0, -0.0, 0.0, -0.0, 1.2855751514434814, -6.5320892333984375, 1.0)
projectionMatrix (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0000200271606445, -1.0, 0.0, 0.0, -0.02000020071864128, 0.0)
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlo

/home/mtrang/anaconda3/envs/drones/lib/python3.8/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


ven = NVIDIA Corporation


array([-0.01666667,  0.        ,  0.05      ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [6]:
env.reset()

array([-0.01666667,  0.        ,  0.05      ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ], dtype=float32)

In [ ]:

done = False
while not done:
    env.render()
    action = env.action_space.sample()
    action = -1 * np.ones_like(action)
    time.sleep(0.05)
    obs, reward, done, info = env.step(action)
    if done:
        env.reset()


In [9]:
#p.loadURDF("../../gym_pybullet_drones/assets/two_corner_room.urdf", [7, -4, 0], physicsClientId=env.CLIENT)
p.loadURDF("../../gym_pybullet_drones/assets/wider_room.urdf", [7, -1.5, 0], physicsClientId=env.CLIENT, globalScaling=1)
#p.removeBody(0)
#id =p.loadSDF("stadium.sdf", physicsClientId=env.CLIENT)
# a1 is a robot
print(id)

6


: 

In [11]:

p.loadURDF("table/table.urdf", [5, 0.5, 0], baseOrientation = [0, 0, 1, 1], physicsClientId=env.CLIENT)
p.loadURDF("table_square/table_square.urdf", [6.5, 0, 0], physicsClientId=env.CLIENT)

10

In [10]:

id = p.loadURDF("../../gym_pybullet_drones/assets/tv_stand.urdf", [3, 0.5, 0], physicsClientId=env.CLIENT, globalScaling=1)
print(id)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/chairs/couch.urdf", [0.7, 0.9, 0], physicsClientId=env.CLIENT, globalScaling=0.7)
print(id)

7
7


In [9]:

id1 = p.loadURDF("../../gym_pybullet_drones/assets/chairs/chair.urdf", [2, -0.7, 0],baseOrientation = [0, 0, -1, 1], physicsClientId=env.CLIENT, globalScaling=1)

In [8]:

id1 = p.loadURDF("../../gym_pybullet_drones/assets/kit_chair.urdf", [5, -0.7, 0],baseOrientation = [0, 0, 2, 1], physicsClientId=env.CLIENT, globalScaling=0.01)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/kit_chair.urdf", [4.5, .4, 0],baseOrientation = [0, 0, 1, 1], physicsClientId=env.CLIENT, globalScaling=0.01)

In [7]:

id1 = p.loadURDF("../../gym_pybullet_drones/assets/dresser.urdf", [3.1, 1., 0.1],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.15)

In [3]:
id1 = p.loadURDF("../../gym_pybullet_drones/assets/lamp/lamp.urdf", [2.5, -0.7, 0.0],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.8)

In [5]:
p.loadURDF("table/table.urdf", [1, 0., 0], baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.7)

14

numActiveThreads = 0
stopping threads
Thread with taskId 0 exiting
Thread TERMINATED
destroy semaphore
semaphore destroyed
destroy main semaphore
main semaphore destroyed
finished


In [8]:

p.loadURDF("table_square/table_square.urdf", [6.5, 0, 0], physicsClientId=env.CLIENT)

id1 = p.loadURDF("../../gym_pybullet_drones/assets/dresser.urdf", [2.1, 1., 0.1],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.15)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/dresser.urdf", [2.1, 0., 0.1],baseOrientation = [0, 0, -1, 1], physicsClientId=env.CLIENT, globalScaling=0.15)
id = p.loadURDF("../../gym_pybullet_drones/assets/tv_stand.urdf", [3, 0.5, 0], baseOrientation=[0,0,1, 1], physicsClientId=env.CLIENT, globalScaling=1)
id = p.loadURDF("../../gym_pybullet_drones/assets/tv_stand.urdf", [1, 0.5, 0], baseOrientation=[0,0,1, 1], physicsClientId=env.CLIENT, globalScaling=1)

id1 = p.loadURDF("../../gym_pybullet_drones/assets/lamp/lamp.urdf", [2.5, -0.7, 0.0],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.8)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/lamp/lamp.urdf", [4.5, -0.7, 0.0],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.8)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/lamp/lamp.urdf", [.5, -0.7, 0.0],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.8)
id1 = p.loadURDF("../../gym_pybullet_drones/assets/lamp/lamp.urdf", [5.5, 0., 0.0],baseOrientation = [0, 0, 0, 1], physicsClientId=env.CLIENT, globalScaling=0.8)

In [7]:
p.removeBody(2)

In [6]:
p.removeBody(id1)

#Single Step of env and print state

In [ ]:

action = env.action_space.sample()
action = -1 * np.ones_like(action)
for i in range(100):
    time.sleep(0.02)
    obs, reward, done, info = env.step(action)
    state = env.getFirstDroneState()
    print(f"action: {action}")
    print(f"obs: {obs}")
    print(f"reward: {reward}")
    print(f"done: {done}")
    print(f"state: {state}")
    env.render()


In [17]:
# try and flip
action = env.action_space.sample()
action = -1 * np.ones_like(action)
action[2] = 1
action[3] = 1
print(action)
for i in range(5):
    time.sleep(0.05)
    obs, reward, done, info = env.step(action)
    state = env.getFirstDroneState()
    print(f"action: {action}")
    print(f"obs: {obs}")
    print(f"reward: {reward}")
    print(f"done: {done}")
    print(f"state: {state}")
    env.render()

[-1. -1.  1.  1.]
[WARNING] it 125 in NavigateMazeAviary._clipAndNormalizeState(), clipped z velocity [-1.20]
action: [-1. -1.  1.  1.]
obs: [ 0.         -0.00908796  0.06283719 -0.7397259  -0.          0.
  0.          0.04953086 -0.33333334 -1.          0.          0.        ]
reward: 0.0
done: True
state: [ 0.00000000e+00 -2.72638831e-01  6.28371889e-01  9.17583522e-01
  0.00000000e+00  0.00000000e+00 -3.97543055e-01 -2.32391733e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  1.48592595e-01
 -1.20236781e+00 -1.63649480e+01  0.00000000e+00  0.00000000e+00
  1.37450068e+04  1.37450068e+04  1.51918496e+04  1.51918496e+04]

[INFO] BaseAviary.render() ——— it 0130 ——— wall-clock time 139.7s, simulation time 0.5s@240Hz (0.00x)
[INFO] BaseAviary.render() ——— drone 0 ——— x +00.00, y -00.27, z +00.63 ——— velocity +00.00, +00.15, -01.20 ——— roll -133.15, pitch -00.00, yaw +00.00 ——— angular velocity -16.3649, +0.0000, +0.0000 ——— 
[WARNING] it 130 in NavigateMazeAviary._clipAndNormalizeS

In [ ]:

landing_zone_xyz = [3.5, 3.5, 0.0625]
position = state[0:3]
print(position)
target_position = landing_zone_xyz
pos_dist = np.linalg.norm(position[0:2] - target_position[0:2])
print(pos_dist)

y_dist = np.linalg.norm(position[2] - (target_position[2] - 0.1))
print(y_dist)

In [ ]:

rpy = state[7:10]
print(rpy)

In [ ]:
# Change initial position of the drones

In [ ]:
env.reset()
p.resetSimulation()